CREATE TABLE articles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    title      VARCHAR(255)                            NOT NULL,
    slug       VARCHAR(255)                            NOT NULL,
    summary    TEXT,
    content    TEXT                                    NOT NULL,
    active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_articles PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_articles_slug ON articles (slug);

CREATE INDEX idx_articles_active ON articles (active);
