-- Создание таблицы courses
CREATE TABLE courses (
                         id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         title VARCHAR(255) NOT NULL,
                         description TEXT,
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Добавление колонки course_id в таблицу modules
ALTER TABLE modules
    ADD COLUMN course_id BIGINT;

-- Создание внешнего ключа
ALTER TABLE modules
    ADD CONSTRAINT fk_modules_courses
        FOREIGN KEY (course_id) REFERENCES courses(id);

-- Создание индекса для ускорения запросов
CREATE INDEX idx_modules_course_id ON modules (course_id);