CREATE TABLE user_progress (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               course_id BIGINT NOT NULL,
                               module_id BIGINT NOT NULL,
                               lesson_id BIGINT,
                               completed_at TIMESTAMP NOT NULL,

                               CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
                               CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES courses(id),
                               CONSTRAINT fk_module FOREIGN KEY (module_id) REFERENCES modules(id),
                               CONSTRAINT fk_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id),

                               CONSTRAINT unique_user_lesson UNIQUE (user_id, lesson_id),
                               CONSTRAINT unique_user_module_completion UNIQUE (user_id, module_id, lesson_id)
);